py.install_sources(
    '002_support_saving_multiple_transit_periods.py',
    '003_align_taz_id_and_node_id.py',
    '004_move_results_to_project.py',
    'migrations.py',
    subdir: 'aequilibrae.project.database_specification.transit.migrations'
)

py.install_sources(
    '000_initial_migration.sql',
    '001_allow_duplicate_nodes.sql',
    subdir: 'aequilibrae.project.database_specification.transit.migrations'
)
