thisdir = 'aequilibrae/project/database_specification/network/migrations'

pyfiles = [
  '000_initial_migration.sql',
  '001_add_cols_to_results.sql',
  '002_add_scenario_table.py',
  '003_add_other_attributes.sql',
  'migrations.py',
]

py.install_sources(
  pyfiles,
  pure: false,
  subdir: thisdir,
)
