py.install_sources(
    '__init__.py',
    'connector_creation.py',
    'gmns_builder.py',
    'gmns_exporter.py',
    'haversine.py',
    'link.py',
    'link_type.py',
    'link_types.py',
    'links.py',
    'mode.py',
    'modes.py',
    'network.py',
    'node.py',
    'nodes.py',
    'period.py',
    'periods.py',
    'safe_class.py',
    subdir: 'aequilibrae.project.network'
)

py.install_sources(
    'network.yml',
    subdir: 'aequilibrae.project.network'
)

subdir('osm')