language: python
python:
  - "3.6"
  - "3.6-dev"
#  - "3.7"
  - "3.7-dev"
os: linux
#virtualenv:
#  system_site_packages: true
before_install:
  - sudo apt-get install -y libspatialite-dev

install:
  - pip install -r requirements.txt
  - pip install numpy --upgrade
  - pip install cython
  - pip install codecov
  - pip install pytest pytest-cov coveralls pycodestyle

script:

  - cd aequilibrae/paths
  - python setup_Assignment.py build_ext --inplace
  - cd ..
  - cd ..
  # or pytest for Python versions 3.6 and higher
  - pytest --cov aequilibrae --cov-report term-missing
after_success:
- coveralls
- codecov
