dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
os: linux
before_install:
  - sudo apt-get install -y libspatialite-dev

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install numpy --upgrade

script:
  - flake8
  - cd aequilibrae/paths
  - python setup_Assignment.py build_ext --inplace
  - cd ..
  - cd ..
  - pytest --cov aequilibrae --cov-report term-missing
after_success:
- coveralls
- codecov
