py.install_sources(
    'agencies.sql',
    'attributes_documentation.sql',
    'fare_attributes.sql',
    'fare_rules.sql',
    'fare_zones.sql',
    'link_types.sql',
    'links.sql',
    'migrations.sql',
    'modes.sql',
    'node_types.sql',
    'nodes.sql',
    'pattern_mapping.sql',
    'route_links.sql',
    'routes.sql',
    'stop_connectors.sql',
    'stops.sql',
    'trigger_settings.sql',
    'trips.sql',
    'trips_schedule.sql',
    'zones.sql',
    subdir: 'aequilibrae.project.database_specification.transit.tables'
)
