py.install_sources(
    '__init__.py',
    'column_order.py',
    'constants.py',
    'date_tools.py',
    'gtfs_loader.py',
    'lib_gtfs.py',
    'parse_csv.py',
    'route_map_matcher.py',
    'route_system.py',
    'transit.py',
    'transit_graph_builder.py',
    subdir: 'aequilibrae.transit'
)

subdir('functions')
subdir('gtfs_writer')
subdir('route_system_reader')
subdir('transit_elements')