thisdir = 'aequilibrae/transit/transit_elements'

pyfiles = [
  '__init__.py',
  'agency.py',
  'basic_element.py',
  'fare.py',
  'fare_rule.py',
  'link.py',
  'mode_correspondence.py',
  'pattern.py',
  'route.py',
  'service.py',
  'stop.py',
  'trip.py',
]

py.install_sources(
  pyfiles,
  pure: false,
  subdir: thisdir,
)
