import logging
import os
import uuid
from pathlib import Path
from typing import TYPE_CHECKING, Protocol, TypedDict

import pandas as pd

from aequilibrae.matrix import AequilibraeMatrix
from aequilibrae.project.project_table import NonSpatialProjectTable
from aequilibrae.utils.db_utils import NestedTransactionManager

logger = logging.getLogger(__name__)

if TYPE_CHECKING:
    from aequilibrae.paths.traffic_assignment import TrafficAssignment


class MatrixRecord(Protocol):
    """Structural type for records generated by :attr:`Matrices.record_type`."""

    name: str
    file_name: str


class SaveSkimsKwargs(TypedDict, total=False):
    """Keyword arguments accepted by :meth:`Matrices.save_skims`."""

    which_ones: str
    format: str
    matrix_name: str | None


class SaveSelectLinkMatricesKwargs(TypedDict, total=False):
    """Keyword arguments accepted by :meth:`Matrices.save_select_link_matrices`."""

    matrix_name: str | None
    format: str


class Matrices(NonSpatialProjectTable[MatrixRecord]):
    """Matrix metadata table with explicit file-managing helpers."""

    name = "matrices"
    key = "name"
    record_name = "MatrixRecord"

    def __init__(self, connection: NestedTransactionManager, matrices_path: str | Path) -> None:
        """Create the matrix metadata table.

        :Arguments:
            **connection** (:obj:`NestedTransactionManager`): Manager for the
            project database containing matrix metadata.

            **matrices_path** (:obj:`str` or :obj:`Path`): Directory containing
            matrix data files.
        """
        super().__init__(connection)
        self.folder: Path = Path(matrices_path)

    def create(self, name: str, file_name: str, matrix: AequilibraeMatrix | None = None) -> MatrixRecord:
        """Create matrix metadata and optionally export matrix data.

        This filesystem operation cannot participate in a project transaction.
        A file supplied for registration remains caller-owned on failure.

        :Arguments:
            **name** (:obj:`str`): Unique matrix name stored in project metadata.

            **file_name** (:obj:`str`): Matrix data file name relative to the
            project's matrix directory.

            **matrix** (:obj:`AequilibraeMatrix`, *Optional*): Matrix to export.
            If omitted, ``file_name`` must already exist.

        :Returns:
            **matrix record** (:obj:`Any`): Generated frozen metadata record.
        """
        self._require_resource_idle()
        path = self.folder / file_name
        if name in self:
            raise ValueError(f"There is already a matrix of name ({name}). It must be unique.")
        if self._transaction_manager.connection.execute(
            "SELECT 1 FROM matrices WHERE file_name=?", (file_name,)
        ).fetchone():
            raise ValueError(f"There is already a matrix record for file name ({file_name}). It must be unique.")

        created = False
        temporary = None
        if matrix is not None and matrix.cores > 0:
            if path.exists():
                raise FileExistsError(f"{file_name} already exists. Choose a different name or matrix format")
            suffix = path.suffix.lower()
            if suffix not in (".omx", ".aem"):
                raise ValueError("Matrix needs to be either OMX or native AequilibraE")
            temporary = path.with_name(f".{path.stem}.{uuid.uuid4().hex}.tmp{suffix}")
            try:
                matrix.export(str(temporary))
                os.replace(temporary, path)
                created = True
            except BaseException:
                if temporary.exists():
                    temporary.unlink()
                raise
            cores = matrix.cores
        else:
            if not path.is_file():
                raise FileNotFoundError(f"{file_name} does not exist. Cannot create this matrix record")
            cores = self.__cores_on_disk(file_name)

        try:
            self.insert(name=name, file_name=file_name, cores=cores)
        except BaseException as primary:
            if created:
                try:
                    path.unlink()
                except BaseException as cleanup:
                    _add_resource_note(primary, f"created matrix remains at {path}: {cleanup!r}")
            raise
        return self.get(name)

    def register_matrix(self, name: str, file_name: str) -> MatrixRecord:
        """Register an existing caller-owned matrix file.

        :Arguments:
            **name** (:obj:`str`): Unique matrix name.

            **file_name** (:obj:`str`): Existing matrix data file name.

        :Returns:
            **matrix record** (:obj:`Any`): Generated frozen metadata record.
        """
        return self.create(name, file_name, matrix=None)

    def delete_matrix(self, name: str) -> None:
        """Delete matrix metadata and its underlying file.

        :Arguments:
            **name** (:obj:`str`): Matrix name to delete.
        """
        self._require_resource_idle()
        record = self.get(name)
        path = self.folder / record.file_name
        tombstone = path.with_name(f".{path.name}.{uuid.uuid4().hex}.deleted")
        moved = False
        if path.exists():
            os.replace(path, tombstone)
            moved = True
        try:
            super().delete(name)
        except BaseException as primary:
            if moved:
                try:
                    os.replace(tombstone, path)
                except BaseException as cleanup:
                    _add_resource_note(primary, f"matrix is stranded at {tombstone}: {cleanup!r}")
            raise
        if moved:
            tombstone.unlink()

    def save_skims(
        self,
        assignment: "TrafficAssignment",
        *,
        which_ones: str = "final",
        format: str = "omx",
        matrix_name: str | None = None,
    ) -> list[MatrixRecord]:
        """Persist skims from a traffic assignment using its procedure ID as their name.

        One matrix is created for each assignment class. Its metadata name and
        filename are ``{procedure_id}_{class_id}`` and
        ``{procedure_id}_{class_id}.{format}``, respectively.

        :Arguments:
            **assignment** (:class:`~aequilibrae.paths.TrafficAssignment`):
            Assignment whose skims will be saved.

            **which_ones** (:obj:`str`): ``"final"``, ``"blended"``, or
            ``"all"``. Defaults to ``"final"``.

            **format** (:obj:`str`): ``"omx"`` or ``"aem"``. Defaults to
            ``"omx"``.

        :Returns:
            Metadata records for the saved skim matrices.
        """
        mat_format = format.lower()

        # Import locally so the project data gateway does not introduce an
        # import-time dependency from paths back to project.
        from aequilibrae.paths.traffic_assignment import TrafficAssignment

        if not isinstance(assignment, TrafficAssignment):
            raise TypeError("assignment must be a TrafficAssignment")
        matrix_name = assignment.procedure_id if matrix_name is None else matrix_name
        if which_ones not in {"final", "blended", "all"}:
            raise ValueError("which_ones must be 'final', 'blended', or 'all'")

        if mat_format not in {"omx", "aem"}:
            raise ValueError("Matrix needs to be either OMX or native AequilibraE")

        records = []
        for traffic_class in assignment.classes:
            final_skims = traffic_class._aon_results.skims
            blended_skims = traffic_class.results.skims
            core_names = []
            if which_ones in {"final", "all"}:
                core_names.extend(f"{core}_final" for core in final_skims.names)
            if which_ones in {"blended", "all"}:
                core_names.extend(f"{core}_blended" for core in blended_skims.names)
            if not core_names:
                continue

            output = AequilibraeMatrix()
            output.create_empty(
                file_name=AequilibraeMatrix().random_name(),
                zones=assignment.classes[0].graph.centroids.shape[0],
                matrix_names=core_names,
                memory_only=False,
            )
            output.index[:] = assignment.classes[0].graph.centroids[:]
            if which_ones in {"final", "all"}:
                for core in final_skims.names:
                    output.matrix[f"{core}_final"][:, :] = final_skims.matrix[core][:, :]
            if which_ones in {"blended", "all"}:
                for core in blended_skims.names:
                    output.matrix[f"{core}_blended"][:, :] = blended_skims.matrix[core][:, :]
            output.matrices.flush()
            output.description = f"Skimming for assignment procedure. Class {traffic_class._id}"

            name = f"{matrix_name}_{traffic_class._id}"
            records.append(self.create(name, f"{name}.{mat_format}", output))
        return records

    def save_select_link_matrices(
        self,
        assignment: "TrafficAssignment",
        *,
        matrix_name: str | None = None,
        format: str = "omx",
    ) -> MatrixRecord:
        """Persist select-link OD matrices from a traffic assignment.

        ``matrix_name`` and ``format`` may be supplied as keyword arguments;
        the matrix name defaults to ``{procedure_id}_select_link_matrices``.
        """
        mat_format = format.lower()
        if mat_format != "omx":
            raise ValueError("select-link matrices must use OMX format")

        from aequilibrae.paths.traffic_assignment import TrafficAssignment

        if not isinstance(assignment, TrafficAssignment):
            raise TypeError("assignment must be a TrafficAssignment")
        matrix_name = f"{assignment.procedure_id}_select_link_matrices" if matrix_name is None else matrix_name

        names = [
            f"{key}_{traffic_class._id}"
            for traffic_class in assignment.classes
            if traffic_class._selected_links is not None
            for key in traffic_class._selected_links
        ]
        if not names:
            raise ValueError("assignment has no select-link matrices to save")

        output = AequilibraeMatrix()
        output.create_empty(
            file_name=AequilibraeMatrix().random_name(),
            zones=assignment.classes[0].graph.centroids.shape[0],
            matrix_names=names,
            memory_only=False,
        )
        output.index[:] = assignment.classes[0].graph.centroids[:]
        for traffic_class in assignment.classes:
            if traffic_class._selected_links is None:
                continue
            matrices = traffic_class.results.select_link_od
            for matrix in matrices.names:
                output.matrix[f"{matrix}_{traffic_class._id}"][:, :] = matrices.get_matrix(matrix)[:, :, 0]
        output.matrices.flush()
        output.description = f"Select link matrix from procedure ID {assignment.procedure_id}_sl."
        return self.create(matrix_name, f"{matrix_name}.{mat_format}", output)

    def get_matrix(self, name: str) -> AequilibraeMatrix:
        """Load matrix data by metadata name.

        :Arguments:
            **name** (:obj:`str`): Registered matrix name.

        :Returns:
            **matrix** (:obj:`AequilibraeMatrix`): Loaded matrix data.
        """
        record = self.get(name)
        matrix = AequilibraeMatrix()
        matrix.load(str(self.folder / record.file_name))
        return matrix

    def check_exists(self, name: str) -> bool:
        """Return whether matrix metadata exists for ``name``.

        :Arguments:
            **name** (:obj:`str`): Matrix name to check.
        """
        return name in self

    def clear_database(self) -> None:
        """Remove metadata records whose files are absent."""
        with self._transaction_manager.transaction() as conn:
            records = conn.execute("SELECT name, file_name FROM matrices").fetchall()
            missing = [(name,) for name, file_name in records if not (self.folder / file_name).is_file()]
            if missing:
                conn.executemany("DELETE FROM matrices WHERE name=?", missing)
        self._invalidate()

    def update_database(self) -> None:
        """Register unrecorded matrix files found in the matrix directory."""
        existing = {record.file_name for record in self}
        for path in self.folder.iterdir():
            if path.name in existing or path.suffix.lower() not in (".omx", ".aem"):
                continue
            candidate = path.name.replace(".", "_").replace(" ", "_")
            name = candidate
            sequence = 0
            while name in self:
                name = f"{candidate}_{sequence}"
                sequence += 1
            self.register_matrix(name, path.name)

    def list(self) -> pd.DataFrame:
        frame = pd.read_sql_query("SELECT * FROM matrices", self._transaction_manager.connection)
        frame["status"] = frame.file_name.map(
            lambda file_name: "" if (self.folder / file_name).is_file() else "file missing"
        )
        return frame

    def _require_resource_idle(self) -> None:
        if self._transaction_manager.in_transaction:
            raise RuntimeError("matrix file helpers cannot run inside a database transaction")

    def __cores_on_disk(self, file_name: str) -> int:
        matrix = AequilibraeMatrix()
        matrix.load(str(self.folder / file_name))
        try:
            return len(matrix.names)
        finally:
            matrix.close()


def _add_resource_note(error: BaseException, message: str):
    if hasattr(error, "add_note"):
        error.add_note(message)
    else:  # pragma: no cover
        logger.error(message)
