py.install_sources(
    '002_add_scenario_table.py',
    'migrations.py',
    subdir: 'aequilibrae.project.database_specification.network.migrations'
)

py.install_sources(
    '000_initial_migration.sql',
    '001_add_cols_to_results.sql',
    subdir: 'aequilibrae.project.database_specification.network.migrations'
)
