thisdir = 'aequilibrae/project/database_specification/network/tables'

pyfiles = [
  'about.sql',
  'attributes_documentation.sql',
  'link_types.sql',
  'links.sql',
  'matrices.sql',
  'migrations.sql',
  'modes.sql',
  'nodes.sql',
  'periods.sql',
  'results.sql',
  'scenarios.sql',
  'transit_graph_configs.sql',
  'zones.sql',
]

py.install_sources(
  pyfiles,
  pure: false,
  subdir: thisdir,
)
