py.install_sources(
    'AoN.pyx',
    'akcelik.pyx',
    'basic_path_finding.pyx',
    'bpr.pyx',
    'bpr2.pyx',
    'conical.pyx',
    'connectivity.pyx',
    'graph_building.pyx',
    'hyperpath.pyx',
    'inrets.pyx',
    'parallel_numpy.pyx',
    'parameters.pxi',
    'path_file_saving.pyx',
    'pq_4ary_heap.pyx',
    'public_transport.pyx',
    'route_choice_link_loading_results.pxd',
    'route_choice_link_loading_results.pyx',
    'route_choice_set.pxd',
    'route_choice_set.pyx',
    'route_choice_set_results.pxd',
    'route_choice_set_results.pyx',
    'route_choice_types.pxd',
    subdir: 'aequilibrae.paths.cython'
)

py.extension_module(
    'AoN',
    'AoN.pyx',
    cpp_args: cpp_args,
    link_args: link_args,
    install: true,
    subdir: 'aequilibrae.paths.cython'
)

py.extension_module(
    'graph_building',
    'graph_building.pyx',
    cpp_args: cpp_args,
    link_args: link_args,
    install: true,
    subdir: 'aequilibrae.paths.cython'
)

py.extension_module(
    'public_transport',
    'public_transport.pyx',
    cpp_args: cpp_args,
    link_args: link_args,
    install: true,
    subdir: 'aequilibrae.paths.cython'
)

py.extension_module(
    'route_choice_link_loading_results',
    'route_choice_link_loading_results.pyx',
    cpp_args: cpp_args,
    link_args: link_args,
    install: true,
    subdir: 'aequilibrae.paths.cython'
)

py.extension_module(
    'route_choice_set',
    'route_choice_set.pyx',
    cpp_args: cpp_args,
    link_args: link_args,
    install: true,
    subdir: 'aequilibrae.paths.cython'
)

py.extension_module(
    'route_choice_set_results',
    'route_choice_set_results.pyx',
    cpp_args: cpp_args,
    link_args: link_args,
    install: true,
    subdir: 'aequilibrae.paths.cython'
)
