thisdir = 'aequilibrae/project/database_specification/network/triggers'

pyfiles = [
  'link_type_table_triggers.sql',
  'modes_table_triggers.sql',
  'network_triggers.sql',
  'periods_triggers.sql',
  'triggers_list.txt',
  'scenarios_triggers.sql',
]

py.install_sources(
  pyfiles,
  pure: false,
  subdir: thisdir,
)
