py.install_sources(
    '__init__.py',
    'context.py',
    'log.py',
    'parameters.py',
    subdir: 'aequilibrae'
)

py.install_sources(
    'parameters.yml',
    subdir: 'aequilibrae'
)

subdir('distribution')
subdir('matrix')
subdir('paths')
subdir('project')
subdir('reference_files')
subdir('transit')
subdir('utils')