assignment:
  equilibrium:
    maximum_iterations: 250
    rgap: 0.0001
distribution:
  gravity:
    max error: 0.0001
    max iterations: 100
    max trip length: -1
  ipf:
    balancing tolerance: 0.001
    convergence level: 0.0001
    max iterations: 5000
network:
  links:
    fields:
      one-way:
      - link_id:
          description: Link ID. THIS FIELD CANNOT BE CHANGED
          type: integer
      - a_node:
          description: Node of origin of the link. THIS FIELD CANNOT BE CHANGED
          type: integer
      - b_node:
          description: Node of destinaiton of the link. THIS FIELD CANNOT BE CHANGED
          type: integer
      - direction:
          description: Direction of the link. THIS FIELD CANNOT BE CHANGED
          type: integer
      - distance:
          description: Length in meters for the link. THIS FIELD CANNOT BE CHANGED
          type: numeric
      - modes:
          description: Set of modes allowed in this link. THIS FIELD CANNOT BE CHANGED
          type: text
      - link_type:
          description: Classification of link (local, arterial, etc). THIS FIELD CANNOT
            BE CHANGED
          osm_source: highway
          type: varchar
      - name:
          description: name
          osm_source: name
          type: text
      - cycleway:
          description: cycleway, both way
          osm_source: cycleway
          type: text
      - cycleway_right:
          description: cycleway, right
          osm_source: cycleway:right
          type: text
      - cycleway_left:
          description: cycleway, left
          osm_source: cycleway:left
          type: text
      - busway:
          description: busway
          osm_source: busway
          type: text
      - busway_right:
          description: busway, right
          osm_source: busway:right
          type: text
      - busway_left:
          description: busway, left
          osm_source: busway:left
          type: text            
      two-way:
      - lanes:
          description: lanes
          osm_behaviour: divide
          osm_source: lanes
          type: integer
      - capacity:
          description: capacity
          type: numeric
      - speed:
          description: speed
          osm_behaviour: copy
          osm_source: maxspeed
          type: numeric
    link_types:
    - centroid_connector:
        description: VIRTUAL centroid connectors only
        lane_capacity: 10000
        lanes: 10
        link_type_id: z
    - default:
        description: Default link type. Due to lack of information
        lane_capacity: 900
        lanes: 2
        link_type_id: y
  modes:
  - car:
      description: All motorized vehicles
      letter: c
  - transit:
      description: All links capable of supporting transit-vehicles
      letter: t
  - walk:
      description: Linkes where walking is permitted
      letter: w
  - bicycle:
      description: All Bicycles
      letter: b
  nodes:
    fields:
    - node_id:
        description: node_id. THIS FIELD CANNOT BE CHANGED
        type: integer
    - is_centroid:
        description: is_centroid
        type: integer
  osm:
    all_link_types:
    - secondary_link
    - escalator
    - trail
    - cycleway
    - path
    - trunk_link
    - secondary
    - escape
    - track
    - road
    - motorway_link
    - primary
    - corridor
    - residential
    - footway
    - motorway
    - primary_link
    - unclassified
    - bus_guideway
    - tertiary_link
    - living_street
    - pedestrian
    - bridleway
    - elevator
    - motor
    - trunk
    - tertiary
    - service
    - steps
    - proposed
    - raceway
    - construction
    - abandoned
    - platform
    - unclassified
    modes:
      bicycle:
        link_types:
        - primary
        - primary_link
        - secondary
        - secondary_link
        - tertiary
        - tertiary_link
        - living_street
        - residential
        - cycleway
        - corridor
        - pedestrian
        - path
        - track
        - trail
        - unclassified
        mode_filter:
          bicycle: 'no'
        unknown_tags: true
      car:
        link_types:
        - motor
        - motorway
        - trunk
        - primary
        - secondary
        - tertiary
        - unclassified
        - residential
        - motorway_link
        - trunk_link
        - primary_link
        - secondary_link
        - tertiary_link
        - living_street
        - service
        - escape
        - road
        mode_filter:
          motor_vehicle: 'no'
        unknown_tags: true
      transit:
        link_types:
        - motor
        - motorway
        - trunk
        - primary
        - secondary
        - tertiary
        - unclassified
        - residential
        - motorway_link
        - trunk_link
        - primary_link
        - secondary_link
        - tertiary_link
        - living_street
        - service
        - escape
        - road
        - bus_guideway
        unknown_tags: true
      walk:
        link_types:
        - cycleway
        - footway
        - steps
        - corridor
        - pedestrian
        - elevator
        - escalator
        - path
        - track
        - trail
        - bridleway
        - unclassified
        mode_filter:
          pedestrian: 'no'
        unknown_tags: true
  gmns:
    critical_dist: 2
    node:
      equivalency:
        node_id: node_id
      fields:
        node_id:
          description: Unique key
          type: integer
          required: true
        name:
          description: Node name
          type: text
          required: false
        x_coord:
          description: Coordinate system specified in GMNS config file
          type: numeric
          required: true
        y_coord:
          description: Coordinate system specified in GMNS config file
          type: numeric
          required: true
        z_coord:
          description: Altitude in short length units
          type: numeric
          required: false
        node_type:
          description: What it represents
          type: text
          required: false
        ctrl_type:
          description: From GMNS ControlType_Set
          type: text
          required: false
        zone_id:
          description: TAZ or city, or census tract
          type: integer
          required: false
        parent_node_id:
          description: The parent of this node
          type: integer
          required: false
    link:
      equivalency:
        link_id: link_id
        a_node: from_node_id
        b_node: to_node_id
        direction: directed
        distance: length
        speed: free_speed
        capacity: capacity
        lanes: lanes
        name: name
        link_type: facility_type
        modes: allowed_uses
        geometry: geometry
      fields:
        link_id:
          description: Primary key
          type: integer
          required: true
        name:
          description: Name
          type: text
          required: false
        from_node_id:
          description: Foreign key (Nodes table)
          type: integer
          required: true
        to_node_id:
          description: Foreign key (Nodes table)
          type: integer
          required: true
        directed:
          description: Whether the link is directed (travel only occurs from the from_node to the to_node) or undirected.
          type: integer
          required: true
        dir_flag:
          description: Shapepoints direction
          type: integer
          required: false
        length:
          description: GMNS length in long_length units
          type: numeric
          required: false
        geometry_id:
          description: Foreign key from geometry table
          type: integer
          required: false
        geometry:
          description: Link geometry, in well-known text (WKT) format.
          type: text
          required: false
        parent_link_id:
          description: The parent of this link
          type: integer
          required: false
        grade:
          description: Percent grade of the link
          type: integer
          required: false
        facility_type:
          description: Facility type (e.g., freeway, arterial, etc.)
          type: text
          required: false
        capacity:
          description: Capacity (veh / hr / lane)
          type: numeric
          required: false
        free_speed:
          description: Free flow speed in long_length units per hour
          type: numeric
          required: false
        lanes:
          description: Number of lanes in the direction of travel
          type: integer
          required: false
        bike_facility:
          description: Type of bicycle accommodation
          type: text
          required: false
        ped_facility:
          description: Type of pedestrian accommodation
          type: text
          required: false
        parking:
          description: Type of parking
          type: text
          required: false
        allowed_uses:
          description: Set of allowed uses
          type: text
          required: false
        toll:
          description: Toll in currency units
          type: numeric
          required: false
        jurisdiction:
          description: Owner/operator of the link
          type: text
          required: false
        row_width:
          description: Width of the entire right-of-way (both directions)
          type: numeric
          required: false
    use_definition:
      fields:
        use:
          description: Short name of the vehicle
          type: text
          required: true
        persons_per_vehicle:
          description: Average persons per vehicle. Used to compute person-based performance measures (0 for non-travel uses)
          type: numeric
          required: true
        pce:
          description: Passenger car equivalents, used for capacity calculations (0 for non-travel uses)
          type: numeric
          required: true
        special_conditions:
          description: Treatment of these special conditions may be needed in a future version of GMNS
          type: text
          required: false
        description:
          description: A longer description of the mode
          type: text
          required: false
      equivalency:
        mode_name: use
osm:
    overpass_endpoint: http://overpass-api.de/api
    nominatim_endpoint: https://nominatim.openstreetmap.org/
    accept_language: "en"
    max_attempts: 50
    timeout: 540
    max_query_area_size: 2500000000
    sleeptime: 5

system:
  cpus: 0
  default_directory: C:\
  logging: true
  logging_directory: /temp/
  temp directory: /temp
