assignment:
  Equilibrium:
    rgap: 1.0e-04
distribution:
  gravity:
    max_error_gravity: 0.0001
    max_iterations_gravity: 100
    max_trip_length: -1
  ipf:
    balancing_tolerance: 0.001
    convergence_level_ipf: 0.0001
    max_iterations_ipf: 5000
system:
  cpus: 8
  projection: 4326
  spatialite_directory: C:\Users\pedro\mod_spatialite-NG-win-amd64\mod_spatialite.dll
  default_directory: C:\Users\pedro\Documents
  driving_side: right
  logging: true
  report zeros: 1
  temp_directory: /temp
network:
  osm:
    max_query_area_size: 2500000000
    timeout: 180
    memory: 0
    infrastructure: 'way["highway"]'
    network_type: 'all_private'
    truncate_by_edge: false
    clean_periphery: true
    retain_all: false
    simplify: true