assignment:
  Equilibrium:
    rgap: 1.0e-04
distribution:
  gravity:
    max error: 0.0001
    max iterations gravity: 100
    max trip length: -1
  ipf:
    balancing tolerance: 0.001
    convergence level: 0.0001
    max iterations ipf: 5000
system:
  cpus: 8
  projection: 4326
  spatialite directory: C:\Users\pedro\mod_spatialite-NG-win-amd64\mod_spatialite.dll
  default_directory: C:\Users\pedro\Documents
  driving side: right
  logging: true
  report zeros: 1
  temp directory: /temp
