name: Benchmarks
on:
  workflow_dispatch:
  pull_request:

env:
  AEQ_SHOW_PROGRESS: "0"
  TNTP_ROOT: ${{ github.workspace }}/TransportationNetworks
  BENCHMARK_REPORTS_DIR: ${{ github.workspace }}/tests/aeq/benchmarks/_convergence_reports
  PYTHON_VERSION: '3.13'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Clone TransportationNetworks
        run: git clone https://github.com/bstabler/TransportationNetworks ${{ env.TNTP_ROOT }}

      - name: Create reports directory
        run: mkdir -p ${{ env.BENCHMARK_REPORTS_DIR }}

      - name: Set up Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python and create virtual environment
        run: uv venv .venv --python ${{ env.PYTHON_VERSION }} --python-preference only-managed  --clear

      - name: Install spatialite
        run: |
          sudo apt update
          sudo apt install -y libspatialite-dev libsqlite3-mod-spatialite
          sudo ln -s /usr/lib/x86_64-linux-gnu/mod_spatialite.so /usr/lib/x86_64-linux-gnu/mod_spatialite

      - name: Install dependencies
        run: uv pip install -e ".[dev]"

      - name: Run benchmarks
        run: uv run pytest tests/aeq/benchmarks/test_anaheim.py --benchmark

      - name: Generate plots
        run: uv run python tests/aeq/benchmarks/plot_benchmarks.py --convergence --compare-flow

      - name: Test adding markdown text to summary 
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY

      - name: Upload plots as artifacts
        uses: actions/upload-artifact@v5
        with:
          name: benchmark-plots
          path: ${{ env.BENCHMARK_REPORTS_DIR }}/**/*.png