name: Python packages for use with QAequilibraE

on:  [pull_request, release]

env:
  QGIS_RELEASE: true


jobs:
  deploy:
    runs-on: ${{ matrix.os}}
    env:
      HAS_SECRETS: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}
      CC: "gcc-12"
      CXX: "g++-12"
    strategy:
      matrix:
        python-version: ['3.9']
        architecture: ['x64']
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set Python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        pip install -r requirements.txt
        pip install -r requirements_additional.txt

    - name: Install dependencies qgis
      run: |
        pip install numpy<1.21

    - name: update versions
      run: |
        cd .github
        python qgis_version.py
        cd ..

    - name: Build
      run: python setup.py bdist_wheel

    - name: Build manylinux Python wheels
      if: ${{matrix.os == 'ubuntu-latest'}}
      uses: RalfG/python-wheels-manylinux-build@v0.7.0
      with:
        python-versions: 'cp39-cp39'
        pip-wheel-args: '--no-deps'

    - name: Moves wheels linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: |
        mkdir -p dist
        cp -v ./*-manylinux*.whl dist/

    - name: Stores artifacts along with the workflow result
      uses: actions/upload-artifact@v3
      with:
        name: library
        path: dist/*.whl
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    - name: Publish
      if: ${{ (github.event_name == 'release') && (env.HAS_SECRETS == 'true') }}
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*.whl
