name: DevelopmentDocumentation

on:  [pull_request]
#on:
#  release:
#    types: [prereleased, published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docs/requirements-docs.txt

    - name: Compile library
      run: |
        cd aequilibrae/paths
        python3 setup_Assignment.py build_ext --inplace
        cd ..
        cd ..

    - name: Build documentation
      run: |
        sphinx-apidoc -T -o docs/source/generated aequilibrae
        cd docs
        make html

    - name: Upload to S3
      uses: thomasattree/mkdocs2S3@master
      with:
        args: --acl public-read --follow-symlinks --delete s3://python/dev/ --recursive
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'dev/'      # optional: defaults to entire repository