name: DevelopmentDocumentation

on:  [pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install -r docs/requirements-docs.txt

    - name: Compile library
      run: |
        cd aequilibrae/paths
        python3 setup_Assignment.py build_ext --inplace
        cd ..
        cd ..

    - name: Build documentation
      run: |
        sphinx-apidoc -T -o docs/source/generated aequilibrae
        cd docs
        make html

  upload_dev:
    needs: build
    if: ${{ github.event_name == 'pull_request'}}
    steps:
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'docs/build/html/'      # optional: defaults to entire repository
          DEST_DIR: 'python/dev/'      # optional: defaults to entire repository

      - name: Check history of versions
        run: python docs/website/check_documentation_versions.py
  upload_final:
    needs: build
    if: ${{ github.event_name == 'release'}}
    steps:
      - name: Upload to S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
            SOURCE_DIR: 'docs/build/html/'      # optional: defaults to entire repository
            DEST_DIR: 'python/latest/'      # optional: defaults to entire repository

      - name: Create Documentation history folder
        run: python docs/website/redir.py

      - name: Upload documentation to history folder
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --exclude '*.py'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'docs/website/'      # optional: defaults to entire repository
          DEST_DIR: 'python/'      # optional: defaults to entire repository

      - name: Upload documentation
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'docs/build/htmlv/'      # optional: defaults to entire repository
          DEST_DIR: 'python/'      # optional: defaults to entire repository
