name: DevelopmentDocumentation

on:  [pull_request]
#on:
#  release:
#    types: [prereleased, published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docs/requirements-docs.txt

    - name: Compile library
      run: |
        cd aequilibrae/paths
        python3 setup_Assignment.py build_ext --inplace
        cd ..
        cd ..

    - name: Build documentation
      run: |
        sphinx-apidoc -T -o docs/source/generated aequilibrae
        cd docs
        make html

    - name: Upload documentation
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.DOC_FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.DOC_FTP_USER }}
        FTP_PASSWORD: ${{ secrets.DOC_FTP_PASSWORD }}
        LOCAL_DIR: docs/build/html/
        REMOTE_DIR: dev/
        ARGS: --transfer-all
