name: Test building Linux Package

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel==0.31.1
        python -m pip install --upgrade cffi setuptools twine

    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2014_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
        build-requirements: 'setuptools numpy cython pyaml pyqt5 requests scipy shapely pandas'
        pip-wheel-args: '--no-deps'