name: Tests Python 3.7

on: [pull_request]
#on:
#  release:
#    types: [prereleased, published]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
#    - name: Set up Python
#      uses: actions/setup-python@v1
#      with:
#        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
#        sudo apt-get update
        sudo apt-get install libsqlite3-mod-spatialite
        sudo apt-get install -y libspatialite-dev
        pip3 install setuptools --upgrade
        pip3 install numpy
        pip3 install pyaml
        pip3 install cython
        pip3 install scipy
        pip3 install openmatrix
        pip3 install pyshp
        pip3 install requests
        pip3 install pytest
        pip3 install spatialite
        pip3 install pytest
        pip3 install pytest-cov
        sudo ln -s /usr/lib/x86_64-linux-gnu/mod_spatialite.so /usr/lib/x86_64-linux-gnu/mod_spatialite

    - name: Compile library
      run: |
        cd aequilibrae/paths
        python3 setup_Assignment.py build_ext --inplace
        cd ..
        cd ..

    - name: Test with coverage report
      run: |
        python3 -m pytest