name: Code coverage

on: [pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      HAS_SECRETS: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libsqlite3-mod-spatialite
        sudo apt install -y libspatialite-dev
        python3 -m pip install setuptools uv --upgrade
        uv pip install . --system
        uv pip install spatialite pytest pytest-cov --system
        sudo ln -s /usr/lib/x86_64-linux-gnu/mod_spatialite.so /usr/lib/x86_64-linux-gnu/mod_spatialite
    - name: Compile library
      run: |
        python3 setup.py build_ext --inplace

    - name: Generate coverage report
      run: |
        python3 -m pytest --cov=aequilibrae tests/
