name: Tests on Windows

on: [pull_request]
#on:
#  release:
#    types: [prereleased, published]

jobs:
  testing:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.7']
#        python-version: [ '3.6', '3.7', '3.8' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set Python environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install numpy cython pyaml pyqt5 pyshp scipy pytest
        choco install visualstudio2019community
        choco install -y microsoft-build-tools visualcppbuildtools --version 14.0.25420.1

    - name: Download spatialite
      run: |
        cd tests
        python setup_windows_spatialite.py
        cd ..

    - name: Compile library
      run: |
        cd aequilibrae/paths
        python setup_Assignment.py build_ext --inplace
        cd ..
        cd ..

    - name: Test with coverage report
      run: |
        python -m pytest