name: Testing on QAequilibraE environment

on: [pull_request]

env:
  QGIS_RELEASE: true


jobs:
  testing:
    runs-on: windows-latest
    env:
      HAS_SECRETS: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        python -m uv pip install -e .[dev]

    - name: Download spatialite on Windows
      if: matrix.os == 'windows-latest'
      run:  python tests/setup_windows_spatialite.py

    - name: Runs test
      run: |
        python -m uv pip install numpy==1.26.4 --force-reinstall
        pytest tests/ --durations=50 --dist=loadscope -n 4 --random-order --verbose
