name: Tests on all platforms with linting

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Set Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          python -m uv pip install ruff==0.12.8

      - name: Lint with ruff
        run: ruff check .

  testing:
    needs: linting
    runs-on: ${{ matrix.os}}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
        os: [windows-latest, ubuntu-latest]
      max-parallel: 20
    steps:
    - uses: actions/checkout@v4
    - name: Set Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        python -m uv pip install -e .[dev]

    - name: Install spatialite
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt update
          sudo apt install libsqlite3-mod-spatialite libspatialite-dev -y
          sudo ln -s /usr/lib/x86_64-linux-gnu/mod_spatialite.so /usr/lib/x86_64-linux-gnu/mod_spatialite
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          python tests/setup_windows_spatialite.py
        fi

    - name: Runs test
      shell: bash
      run: pytest tests/ --durations=50 --dist=loadscope -n 4 --random-order --verbose

  testingMacOS:
    needs: linting
    runs-on: 	macos-13
    env:
      CC: gcc-12
      CXX: g++-12
      MACOSX_DEPLOYMENT_TARGET: 13.0
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      max-parallel: 20
    steps:
    - uses: actions/checkout@v4
    - name: Set Python environment
      uses: actions/setup-python@v5
      with:
        python-version: { matrix.python-version }

    - name: Install spatialite
      shell: bash
      run: |
        brew update
        brew install sqlite
        brew install sqlite libspatialite
        export CPPFLAGS="-I$(brew --prefix sqlite)/include"
        export LDFLAGS="-L$(brew --prefix sqlite)/lib"
        python -m pip install --force-reinstall --no-binary=:all: pysqlite3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        python -m uv pip install -e .[dev]

    - name: Runs test
      shell: bash
      run: pytest tests/ --durations=50 --dist=loadscope -n 3 --random-order --verbose
